record_working_time:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: hrworks
    start:
      required: true
      example: "2026-10-02T08:30:00+02:00"
      selector:
        text:
    end:
      required: true
      example: "2026-10-02T12:00:00+02:00"
      selector:
        text:
    type:
      default: working_time
      selector:
        select:
          translation_key: working_time_type
          options:
            - working_time
            - doctors_appointment
            - business_errand
            - education_and_training
    comment:
      selector:
        text:
    dry_run:
      default: true
      selector:
        boolean:
